### ISSUE TITLE
The plugin cannot use credentials generated by WIF

### ISSUE THREAD

**Issue by KengoTODA** [tehlers/gradle-gcs-build-cache#10]
Hello :wave:,

When I build my project with Gradle 7.6 and Java 11, found that this plugin ended with the following exception:

```
* What went wrong:
Gradle could not start your build.
> Could not create service of type BuildCacheController using .createBuildCacheController().
   > When specifying a JSON credential type, the subject_token_field_name must be set.
```

Note that the credential was generated by WIF like below:

```yml
# .circleci/config.yml
      - gcp-cli/setup:
          use_oidc: true
      - run: ./gradlew build
```

The root cause seems to be that `google-auth-library-java` used by this plugin is `v1.0.0`, and does not contain [the bugfix released in 1.4.0](https://github.com/googleapis/google-auth-library-java/pull/822).

I'll try to find a way to fix this issue later, but let me open an issue for sharing. Thank you!
